### ISSUE TITLE
FYI: maintainer requested on original repo

### ISSUE THREAD

**Issue by nielsbom** [johnalanwoods/maintained-modern-unix#3]
Hi John,

I love the "willing-to-take-over" attitude :-) Thank you for your work!

Just as an FYI in case you missed it: [@ibraheemdev invited you to become a maintainer for the original repo](https://github.com/ibraheemdev/modern-unix/issues/137#issuecomment-1906980592).

If you want to increase the "reach" of your efforts my advice would be to take Ibraheem up on their invitation.

I'm starring your fork too btw, just in case :-)

**Comment by johnalanwoods** [comment]
thanks!
