### ISSUE TITLE
ripgrep-all

### ISSUE THREAD

**Issue by Germano0** [johnalanwoods/maintained-modern-unix#7]
I think [ripgrep-all](https://github.com/phiresky/ripgrep-all) should be added to the list. It makes use of `ripgrep` engine to search inside a multitude of file types. For example I use it to replace `pdfgrep`

**Comment by johnalanwoods** [comment]
Definitely! Feel like making a PR?

**Comment by Germano0** [comment]
Sure, I will do it as soon as possible

**Comment by Germano0** [comment]
https://github.com/johnalanwoods/maintained-modern-unix/pull/8

**Comment by johnalanwoods** [comment]
Thank you!

Closing as complete.
