### ISSUE TITLE
Consider adding `dua` and `difftastic`

### ISSUE THREAD

**Issue by lnicola** [johnalanwoods/maintained-modern-unix#9]
[`dua`](https://github.com/Byron/dua-cli/) is similar to `dust`, but still pretty nice and it has an interactive mode where you can navigate through the directory hierarchy.

[`difftastic`](https://github.com/Wilfred/difftastic) is a structural diff tool.

**Comment by yozachar** [comment]
PRs are welcome!

**Comment by lnicola** [comment]
Sure, will try, unless someone beats me to it.

**Comment by johnalanwoods** [comment]
any update?

**Comment by johnalanwoods** [comment]
Closing as discussion moved to PR.
